"""Shared sprite-sheet font config."""

ARCADE_FONT_PATH = "assets/texture/ArcadeFont.png"
ARCADE_FONT_CHARSET = "ABCDEFGHIJKLMNO_PQRSTUVWXYZ!?pts0123456789/-'_ "
ARCADE_FONT_CHAR_WIDTH = 8
ARCADE_FONT_CHAR_HEIGHT = 8
ARCADE_FONT_COLUMNS = 16
