[tool.mypy]
python_version = "3.9"
explicit_package_bases = true
namespace_packages = true
python_path = "."
warn_return_any = true
warn_unused_configs = true
disallow_any_unimported = false
disallow_subclassing_any = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
exclude = "^(minilibx-linux/|.venv/|libs/)"

[[tool.mypy.overrides]]
module = "Engine.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "mazegenerator.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "assets.code.actors.*"
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = "assets.code.components.*"
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = "game.*"
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = "*.__init__"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[project]
name = "Pac-man"
version = "1.0.0"
description = "Pac-Man Game"
authors = [
    {name = "nbreton"},
    {name = "erxia"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pydantic"
]

[tool.flake8]
max-line-length = 79
max-complexity = 10
exclude = [
    ".git",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".venv",
    "venv",
    "libs",
    "Pac_man.egg-info",
    "logs",
    "docs",
    "minilibx-linux"
]
ignore = [
    "E203",
    "E266",
    "W503",
    "F401",
    "F403",
    "F405",
    "E741",
]
per-file-ignores = [
    "*/__init__.py:F401",
]

